module InformationConstant
  KINDS = [
    :hma, :ip_vanish, :vidoza_ip_vanish, :openload_ip_vanish,
    :openload_express_vpn, :openload_pure_vpn, :openload_hma
  ]

  CONFIG_JSON_PATH = File.dirname(__FILE__) + "/../../configs/config.json"
  SITE_NAME = "%{site_name}"
  MACHINE_ID = "%{id}"
  LINKS_TXT = "links.txt"
  USERNAME = "%{username}"
  PASSWORD = "%{password}"
  EXPRESS_VPN_KEY = "%{express_vpn_key}"

  HMA_SPREAD_SHEET_KEY = "1-4mkLJsGplHni4ZlfVhcOQGioId4wom-grHZqhXd2F4"
  HMA_FOLDER = File.dirname(__FILE__) + "/../../tmp"
  HMA_LINKS_FOLDER = "#{HMA_FOLDER}/links"
  HMA_LINK_FILE_NAME_PATTERN = "#{HMA_LINKS_FOLDER}/#{SITE_NAME}.txt"
  HMA_MACHINES_INFO_FOLDER = "#{HMA_FOLDER}/machines_info"
  HMA_MACHINE_FOLDER_NAME_PATTERN = "#{HMA_MACHINES_INFO_FOLDER}/#{MACHINE_ID}"
  HMA_ANTI_CAPTCHA_TXT = "#{HMA_FOLDER}/anti_captcha.txt"
  HMA_ACCOUNT_TXT_PATTERN = "#{HMA_MACHINE_FOLDER_NAME_PATTERN}/VPN_account.txt"
  HMA_ACCOUNT_FILE_CONTENT_FORMAT = "#{USERNAME}|#{PASSWORD}"

  # Ip vanish
  IP_VANISH_SPREAD_SHEET_KEY = "107EibzqLaItRIXpPdkFH4J00oQyzs0_OzIZZCHqeb9Y"
  IP_VANISH_FOLDER = File.dirname(__FILE__) + "/../../tmp/ip_vanish"
  IP_VANISH_LINKS_FOLDER = "#{IP_VANISH_FOLDER}/links"
  IP_VANISH_LINK_FILE_NAME_PATTERN = "#{IP_VANISH_LINKS_FOLDER}/#{SITE_NAME}.txt"
  IP_VANISH_MACHINES_INFO_FOLDER = "#{IP_VANISH_FOLDER}/machines_info"
  IP_VANISH_MACHINE_FOLDER_NAME_PATTERN = "#{IP_VANISH_MACHINES_INFO_FOLDER}/#{MACHINE_ID}"
  IP_VANISH_ANTI_CAPTCHA_TXT = "#{IP_VANISH_FOLDER}/anti_captcha.txt"
  IP_VANISH_ACCOUNT_TXT_PATTERN = "#{IP_VANISH_MACHINE_FOLDER_NAME_PATTERN}/ip_vanish_password.txt"
  IP_VANISH_ACCOUNT_FILE_CONTENT_FORMAT = "#{USERNAME}\n#{PASSWORD}"

  # VIDOZA - ip vanish
  VIDOZA_IP_VANISH_SPREAD_SHEET_KEY = "1pFmMh6eHvMLtC2bSO6_eOnBz_H6lD8odrGdcEgA5PO4"
  VIDOZA_IP_VANISH_FOLDER = File.dirname(__FILE__) + "/../../tmp/vidoza_ip_vanish"
  VIDOZA_IP_VANISH_LINKS_FOLDER = "#{VIDOZA_IP_VANISH_FOLDER}/links"
  VIDOZA_IP_VANISH_LINK_FILE_NAME_PATTERN = "#{VIDOZA_IP_VANISH_LINKS_FOLDER}/#{SITE_NAME}.txt"
  VIDOZA_IP_VANISH_MACHINES_INFO_FOLDER = "#{VIDOZA_IP_VANISH_FOLDER}/machines_info"
  VIDOZA_IP_VANISH_MACHINE_FOLDER_NAME_PATTERN = "#{VIDOZA_IP_VANISH_MACHINES_INFO_FOLDER}/#{MACHINE_ID}"
  VIDOZA_IP_VANISH_ANTI_CAPTCHA_TXT = "#{VIDOZA_IP_VANISH_FOLDER}/anti_captcha.txt"
  VIDOZA_IP_VANISH_ACCOUNT_TXT_PATTERN = "#{VIDOZA_IP_VANISH_MACHINE_FOLDER_NAME_PATTERN}/ip_vanish_password.txt"
  VIDOZA_IP_VANISH_ACCOUNT_FILE_CONTENT_FORMAT = "#{USERNAME}\n#{PASSWORD}"

  # OPENLOAD - ip vanish
  OPENLOAD_IP_VANISH_SPREAD_SHEET_KEY = "19lIhtq4aapAzmNFJKyYLrjckWgkwJJF-SoFkeb5V-vE"
  OPENLOAD_IP_VANISH_FOLDER = File.dirname(__FILE__) + "/../../tmp/openload_ip_vanish"
  OPENLOAD_IP_VANISH_LINKS_FOLDER = "#{OPENLOAD_IP_VANISH_FOLDER}/links"
  OPENLOAD_IP_VANISH_LINK_FILE_NAME_PATTERN = "#{OPENLOAD_IP_VANISH_LINKS_FOLDER}/#{SITE_NAME}.txt"
  OPENLOAD_IP_VANISH_MACHINES_INFO_FOLDER = "#{OPENLOAD_IP_VANISH_FOLDER}/machines_info"
  OPENLOAD_IP_VANISH_MACHINE_FOLDER_NAME_PATTERN = "#{OPENLOAD_IP_VANISH_MACHINES_INFO_FOLDER}/#{MACHINE_ID}"
  OPENLOAD_IP_VANISH_ANTI_CAPTCHA_TXT = "#{OPENLOAD_IP_VANISH_FOLDER}/anti_captcha.txt"
  OPENLOAD_IP_VANISH_ACCOUNT_TXT_PATTERN = "#{OPENLOAD_IP_VANISH_MACHINE_FOLDER_NAME_PATTERN}/ip_vanish_password.txt"
  OPENLOAD_IP_VANISH_ACCOUNT_FILE_CONTENT_FORMAT = "#{USERNAME}\n#{PASSWORD}"

  # OPENLOAD - express_vpn
  OPENLOAD_EXPRESS_VPN_SPREAD_SHEET_KEY = "16fIHyfySEdSOrwGp3YpDDvS5ZXJwdbqUuiuDNSnXVc8"
  OPENLOAD_EXPRESS_VPN_FOLDER = File.dirname(__FILE__) + "/../../tmp/openload_express_vpn"
  OPENLOAD_EXPRESS_VPN_LINKS_FOLDER = "#{OPENLOAD_EXPRESS_VPN_FOLDER}/links"
  OPENLOAD_EXPRESS_VPN_LINK_FILE_NAME_PATTERN = "#{OPENLOAD_EXPRESS_VPN_LINKS_FOLDER}/#{SITE_NAME}.txt"
  OPENLOAD_EXPRESS_VPN_MACHINES_INFO_FOLDER = "#{OPENLOAD_EXPRESS_VPN_FOLDER}/machines_info"
  OPENLOAD_EXPRESS_VPN_MACHINE_FOLDER_NAME_PATTERN = "#{OPENLOAD_EXPRESS_VPN_MACHINES_INFO_FOLDER}/#{MACHINE_ID}"
  OPENLOAD_EXPRESS_VPN_ANTI_CAPTCHA_TXT = "#{OPENLOAD_EXPRESS_VPN_FOLDER}/anti_captcha.txt"
  OPENLOAD_EXPRESS_VPN_ACCOUNT_TXT_PATTERN = "#{OPENLOAD_EXPRESS_VPN_MACHINE_FOLDER_NAME_PATTERN}/express_vpn_password.txt"
  OPENLOAD_EXPRESS_VPN_ACCOUNT_FILE_CONTENT_FORMAT = "#{USERNAME}\n#{PASSWORD}"

  OPENLOAD_EXPRESS_SOFT_VPN_ACCOUNT_TXT_PATTERN = "#{OPENLOAD_EXPRESS_VPN_MACHINE_FOLDER_NAME_PATTERN}/VPN_account.txt"
  OPENLOAD_EXPRESS_SOFT_VPN_ACCOUNT_FILE_CONTENT_FORMAT = "#{USERNAME}|#{PASSWORD}|#{EXPRESS_VPN_KEY}"

  # OPENLOAD - pure_vpn
  OPENLOAD_PURE_VPN_SPREAD_SHEET_KEY = "1mmo_mLkxWd5KITAdumneyvfeuZ02clwQTvy57buSWpo"
  OPENLOAD_PURE_VPN_FOLDER = File.dirname(__FILE__) + "/../../tmp/openload_pure_vpn"
  OPENLOAD_PURE_VPN_LINKS_FOLDER = "#{OPENLOAD_PURE_VPN_FOLDER}/links"
  OPENLOAD_PURE_VPN_LINK_FILE_NAME_PATTERN = "#{OPENLOAD_PURE_VPN_LINKS_FOLDER}/#{SITE_NAME}.txt"
  OPENLOAD_PURE_VPN_MACHINES_INFO_FOLDER = "#{OPENLOAD_PURE_VPN_FOLDER}/machines_info"
  OPENLOAD_PURE_VPN_MACHINE_FOLDER_NAME_PATTERN = "#{OPENLOAD_PURE_VPN_MACHINES_INFO_FOLDER}/#{MACHINE_ID}"
  OPENLOAD_PURE_VPN_ANTI_CAPTCHA_TXT = "#{OPENLOAD_PURE_VPN_FOLDER}/anti_captcha.txt"
  OPENLOAD_PURE_VPN_ACCOUNT_TXT_PATTERN = "#{OPENLOAD_PURE_VPN_MACHINE_FOLDER_NAME_PATTERN}/pure_vpn_password.txt"
  OPENLOAD_PURE_VPN_ACCOUNT_FILE_CONTENT_FORMAT = "#{USERNAME}\n#{PASSWORD}"

  # OPENLOAD - hma
  OPENLOAD_HMA_SPREAD_SHEET_KEY = "1hx9UB3GlMN84Gc_V4UFwBvlTWNT6s9T_tJ05BkCJSLI"
  OPENLOAD_HMA_FOLDER = File.dirname(__FILE__) + "/../../tmp/openload_hma"
  OPENLOAD_HMA_LINKS_FOLDER = "#{OPENLOAD_HMA_FOLDER}/links"
  OPENLOAD_HMA_LINK_FILE_NAME_PATTERN = "#{OPENLOAD_HMA_LINKS_FOLDER}/#{SITE_NAME}.txt"
  OPENLOAD_HMA_MACHINES_INFO_FOLDER = "#{OPENLOAD_HMA_FOLDER}/machines_info"
  OPENLOAD_HMA_MACHINE_FOLDER_NAME_PATTERN = "#{OPENLOAD_HMA_MACHINES_INFO_FOLDER}/#{MACHINE_ID}"
  OPENLOAD_HMA_ANTI_CAPTCHA_TXT = "#{OPENLOAD_HMA_FOLDER}/anti_captcha.txt"
  OPENLOAD_HMA_ACCOUNT_TXT_PATTERN = "#{OPENLOAD_HMA_MACHINE_FOLDER_NAME_PATTERN}/hma_password.txt"
  OPENLOAD_HMA_ACCOUNT_FILE_CONTENT_FORMAT = "#{USERNAME}\n#{PASSWORD}"

  WORKSHEETS = {
    links: {id: 0, url: 1},
    vpn_accounts: {id: 1, username: 1, password: 2, key: 3, machine_id: 4, type: 5},
    machines_list: {id: 2, machine_id: 1, status: 2, account_id: 3, updated_links_at: 4},
    anti_captcha: {id: 3, key: 1},
    special_links: {id: 4, url: 1}
  }
end
